version: '3.8'

services:
  schedulesync_api:
    build:
      context: .
    container_name: schedulesync_api
    ports:
      - "5004:5004"
    depends_on:
      - db
    networks:
      - monitoring_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

networks:
  monitoring_network:
    external: true
