services:
  schedulesync_api:
    build:
      context: .
      dockerfile: ScheduleSync.API/Dockerfile
    container_name: schedulesync_api
    ports:
      - "5004:80"  # 🔹 Porta exposta corretamente
    networks:
      - monitoring_network  # 🔹 Compartilha a mesma redes
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

networks:
  monitoring_network:
    external: true  # 🔹 Garante que todas as APIs se comuniquem
